# Change these first
owner: skurtzemann # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Blog
    url: https://kurtzemann.fr/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.kurtzemann.fr
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: 
  navbar:
    - title: Blog
      href: https://kurtzemann.fr
    - title: Status
      href: https://status.kurtzemann.fr
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
